name: app_files_setup
description: A package that simplifies the task of organizing files and folders to quick start development.
version: 1.0.1
maintainer: Muzammil Dafedar(@MujmillahammedDafedar)
homepage: https://github.com/MujmillahammedDafedar/app_files_setup

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0